name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Odin
        uses: laytan/setup-odin@v2
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            release: latest

      - name: Check Odin Version
        run: odin version

      - name: Build Project
        run: odin build . -vet -strict-style
